version: "3.9"
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/data/workspaces:/backend/workspaces
      - ./backend/data/TofDaq:/backend/TofDaq
    stdin_open: true  
    tty: true
    network_mode: "host"
    environment:
      - MASCOPE_ENV=docker
  frontend:
    build:
      context: ./frontend
    volumes:
      - /tmp/.X11-unix:/temp/.X11-unix
      - ./frontend/src:/frontend/src
    environment:
      - DISPLAY
    network_mode: "host"
    ipc: host
    mem_limit: 4g