version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./testdata:/data
      - ./backend:/backend
    stdin_open: true  
    tty: true
    network_mode: "host"
    environment:
      - MASCOPE_ENV=docker
      - MASCOPE_DATADIR=/data
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/frontend/src
    network_mode: "host"