version: "3.9"
services:
  backend:
    build:
      context: ./karsa-backend
    volumes:
      - ./karsa-backend/src:/karse-backend/src
      - ./karsa-backend/Data/Projects:/karsa-backend/Projects
      - ./karsa-backend/Data/TofDaq:/karsa-backend/TofDaq
    stdin_open: true  
    tty: true
    network_mode: "host"
  electron:
    build:
      context: ./karsa-electron
    volumes:
      - /tmp/.X11-unix:/temp/.X11-unix
      - ./karsa-electron/src:/karsa-electron/src
      - ./karsa-electron/configs:/karsa-electron/configs
    environment:
      - DISPLAY
    network_mode: "host"