#!/usr/bin/env bash

# get script path helpers

script=$(basename ${BASH_SOURCE[0]})
directory=$(dirname "${BASH_SOURCE[0]}")

# set font formatting helpers

n=$(tput sgr0)
u=$(tput smul)
b=$(tput bold)

# set compose base command

function compose {
    docker-compose -f "${directory}/docker-compose.yml" "$@"
}

# help function

function help {
    echo -e \\n"${b}${script}${n} - CLI for Karsa's Mascope software"
    echo "

    ${u}Usage:${n}

        mascope [subcommand] [options]

    ${u}Subcommands:${n}

        ${b}mascope up${n}              Starts all services

        ${b}mascope down${n}            Stops all services

        ${b}mascope cycle${n}           Restarts all services

            cycle options:
                -r | --rebuild                          Rebuild all
                -r [service] | --rebuild=[service]      Rebuild service

        ${b}mascope status${n}          Displays service status
        
        ${b}mascope logs [service]${n}  Attaches to service logs

        ${b}mascope help | -h${n}       Print this help message
    "
    exit 1;
}

# print help if no arguments supplied

if [[ "$1" == "--" ]]; then help; fi

# parse subcommand

case "$1" in
  up) subcommand="$1"; shift 1;;
  down) subcommand="$1"; shift 1;;
  cycle) subcommand="$1"; shift 1;;
  status) subcommand="$1"; shift 1;;
  logs) subcommand="$1"; shift 1;;

  -h | --help | help) help;;
  *) "unknown subcommand $1"; help;;
esac

# execute subcommmand

if [[ "${subcommand}" = "up" ]]; then
    echo "Starting mascope services..."
    compose up -d
fi

if [[ "${subcommand}" = "down" ]]; then
    echo "Stopping mascope services..."
    compose down
fi

if [[ "${subcommand}" = "cycle" ]]; then
    rebuild="none"
    while [ "$#" -gt 0 ]; do
      case "$1" in
        -r | --rebuild) 
            if [[ "$2" == "--" ]]; then 
                shift 1; break;
            else
                rebuild="$2"; shift 2; break;
            fi ;;
        -*) echo "unknown cycle option: $1" >&2; help;;
        *) echo "unexpected cycle argument: $1" >&2; help;;
      esac
    done
    if [ "${rebuild}" = "none" ]; then
        echo "Restarting mascope services..."
        compose restart
    elif [ "${rebuild}" = "backend" ]; then
        echo "Restarting mascope services and rebuilding backend..."
        compose down && compose build backend && compose up -d
    elif [ "${rebuild}" = "frontend" ]; then
        echo "Restarting mascope services and rebuilding backend..."
        compose down && compose build frontend && compose up -d
    else
        echo "Restarting mascope services and rebuilding services..."
        compose down && compose build && compose up -d
    fi
fi

if [ "${subcommand}" = "status" ]; then
    compose ps
fi

if [ ${subcommand} = "logs" ]; then
    case "$1" in
        frontend | f ) target="frontend";;
        backend | b ) target="backend";;

        *) echo "unknown log target $1" >&2; help;;
    esac
    if [[ "${target}" = "frontend" ]]; then
        compose logs -f frontend
    elif [[ "${target}" = "backend" ]]; then
        docker exec -it mascope-backend-1 /bin/bash -c 'tmux attach -t karsa-services'
    fi
fi

exit 0;