import asyncio
import datetime
import json
import nest_asyncio
import os
import pandas as pd
import sqlite3
import shutil

from scipy.io import loadmat

from backend.db.id import gen_id
from backend.lib.file import filename_to_zarr_path, load_file

# patch asyncio to supported run_until_complete
# when an event loop is already running
nest_asyncio.apply()


def load_peakshape_mat(peakshape_file):
    """Load peakshape from a file generated by tofTools"""
    ps_mat = loadmat(peakshape_file)
    ps_struct = ps_mat["peakShape"]
    ps = ps_struct["dat"][0][0]
    x = ps[:, 0]
    y = ps[:, 1]
    y = y / max(y)
    return {"x": x, "y": y}


def run():
    data_path = os.environ.get("MASCOPE_PRIVATE_DATABASE_DIR")

    # STEP 1 - setup new database
    old_db_path = os.path.join(data_path, "mascope.v2.db")
    new_db_path = os.path.join(data_path, "mascope.v3.db")
    shutil.copyfile(old_db_path, new_db_path)
    new_conn = sqlite3.connect(database=new_db_path)
    with new_conn:
        # Create instrument function table
        new_conn.execute(
            """--sql
            CREATE TABLE instrument_function (
                instrument_function_id VARCHAR(32) PRIMARY KEY
                ,instrument VARCHAR(64)
                ,datetime_utc TIMESTAMP
                ,peakshape JSON
                ,resolution_function JSON
            );
        """
        )

        # Populate
        peakshape_path = os.path.join(
            os.path.dirname(os.path.realpath(__file__)), "peakshapes"
        )
        instrument_function_data = []

        # TODO KLTOF2
        instrument = "KLTOF2"
        peakshape_file = os.path.join(peakshape_path, "20221129T135120.mat")
        peakshape = load_peakshape_mat(peakshape_file)
        R_p1 = 0.0001097
        R_p2 = 0.002287
        timestamp = datetime.datetime(1970, 1, 1)
        instrument_function_data.append(
            (
                gen_id(length=32),
                instrument,
                timestamp.isoformat(),
                json.dumps({"x": list(peakshape["x"]), "y": list(peakshape["y"])}),
                json.dumps([R_p1, R_p2]),
            )
        )
        #
        # KLTOF2
        # 20210831-DannyExplosivesBr
        instrument = "KLTOF2"
        peakshape_file = os.path.join(peakshape_path, "20221129T135120.mat")
        peakshape = load_peakshape_mat(peakshape_file)
        R_p1 = 0.0001097
        R_p2 = 0.002287
        timestamp = datetime.datetime(2021, 8, 31)
        instrument_function_data.append(
            (
                gen_id(length=32),
                instrument,
                timestamp.isoformat(),
                json.dumps({"x": list(peakshape["x"]), "y": list(peakshape["y"])}),
                json.dumps([R_p1, R_p2]),
            )
        )
        # 20220127_Danny_DMNB_UN
        instrument = "KLTOF2"
        peakshape_file = os.path.join(peakshape_path, "20221202T102104.mat")
        peakshape = load_peakshape_mat(peakshape_file)
        R_p1 = 0.0001258
        R_p2 = 0.001769
        timestamp = datetime.datetime(2022, 1, 27)
        instrument_function_data.append(
            (
                gen_id(length=32),
                instrument,
                timestamp.isoformat(),
                json.dumps({"x": list(peakshape["x"]), "y": list(peakshape["y"])}),
                json.dumps([R_p1, R_p2]),
            )
        )
        # 20220329_DannyMix_ng1-100_pLCVAR_pg1
        instrument = "KLTOF2"
        peakshape_file = os.path.join(peakshape_path, "20221205T111017.mat")
        peakshape = load_peakshape_mat(peakshape_file)
        R_p1 = 0.0001397
        R_p2 = 8.97e-05
        timestamp = datetime.datetime(2022, 1, 27)
        instrument_function_data.append(
            (
                gen_id(length=32),
                instrument,
                timestamp.isoformat(),
                json.dumps({"x": list(peakshape["x"]), "y": list(peakshape["y"])}),
                json.dumps([R_p1, R_p2]),
            )
        )
        # 20220714_CBS_TDG_DBrMe_LOD-MeOH
        instrument = "KLTOF2"
        peakshape_file = os.path.join(peakshape_path, "20221205T140252.mat")
        peakshape = load_peakshape_mat(peakshape_file)
        R_p1 = 0.0001497
        R_p2 = 0.0003698
        timestamp = datetime.datetime(2022, 1, 27)
        instrument_function_data.append(
            (
                gen_id(length=32),
                instrument,
                timestamp.isoformat(),
                json.dumps({"x": list(peakshape["x"]), "y": list(peakshape["y"])}),
                json.dumps([R_p1, R_p2]),
            )
        )
        #

        # TODO: KLTOF1
        instrument = "KLTOF1"
        peakshape_file = os.path.join(peakshape_path, "20221202T101822.mat")
        peakshape = load_peakshape_mat(peakshape_file)
        R_p1 = 9.01e-05
        R_p2 = 0.0006993
        timestamp = datetime.datetime(1970, 1, 1)
        instrument_function_data.append(
            (
                gen_id(length=32),
                instrument,
                timestamp.isoformat(),
                json.dumps({"x": list(peakshape["x"]), "y": list(peakshape["y"])}),
                json.dumps([R_p1, R_p2]),
            )
        )
        # KLTOF1
        instrument = "KLTOF1"
        peakshape_file = os.path.join(peakshape_path, "20221202T101822.mat")
        peakshape = load_peakshape_mat(peakshape_file)
        R_p1 = 9.01e-05
        R_p2 = 0.0006993
        timestamp = datetime.datetime(2022, 11, 10)
        instrument_function_data.append(
            (
                gen_id(length=32),
                instrument,
                timestamp.isoformat(),
                json.dumps({"x": list(peakshape["x"]), "y": list(peakshape["y"])}),
                json.dumps([R_p1, R_p2]),
            )
        )
        #

        instrument_function_df = pd.DataFrame.from_records(
            instrument_function_data,
            columns=(
                "instrument_function_id",
                "instrument",
                "datetime_utc",
                "peakshape",
                "resolution_function",
            ),
        )
        instrument_function_df.to_sql(
            "instrument_function", new_conn, if_exists="append", index=False
        )

        # Delete sample file records without file
        filenames = pd.read_sql(
            """--sql
            SELECT
                filename
            FROM sample_file
            """,
            new_conn,
        ).filename.tolist()
        sample_files_to_delete = []
        for filename in filenames:
            try:
                load_file(filename, vars=[])
            except FileNotFoundError:
                sample_files_to_delete.append(filename)
        for i in range(0, len(sample_files_to_delete), 100):
            to_delete_now = sample_files_to_delete[i : i + 100]
            sample_filename_refs = ",".join("?" * len(to_delete_now))
            new_conn.cursor().execute(
                f"""--sql
                DELETE FROM sample_file
                WHERE filename IN ({sample_filename_refs})
                """,
                to_delete_now,
            )

        # Delete all peak datasets
        for filename in filenames:
            peaks_path = filename_to_zarr_path(filename, "peaks")
            try:
                shutil.rmtree(peaks_path)
            except Exception as e:
                print(e)

        # Delete all matches
        new_conn.cursor().execute(
            f"""--sql
            DELETE FROM match
        """
        )
    new_conn.commit()
    new_conn.close()
