# -*- coding: utf-8 -*-
"""Definitions of functions and classes modeling the physical features of an
MS instrument, such as the resolution, peak shape etc.

Created on Tue Apr  2 13:05:14 2019

@author: Karsa
"""

import numpy as np

from scipy.io import loadmat
from scipy.sparse import lil_matrix
from sklearn.preprocessing import normalize

from .lib.TwTool import TwTof2Mass, TwMass2Tof


class KInstrument():
    """Base class holding the properties of the TOF-MS instrument,
    namely TofDaq and TPS configuration, peak shape, resolution function
    and SIS.

    Attributes
    ----------
    desc : TSharedMemoryDesc or TwH5Desc
        Tofwerk data descriptor (H5/ShMem)
    time_res : float
        Instrument time resolution (seconds)
    mz_par : array
        Mass calibration parameters
    mz_mode : int
        Mass calibration mode
    ps : dict
        Single peak shape dictionary with vectors x and y
    peakshapes : dict
        Dictionary of multiple peak shapes, keys being the sample
        number for which the peak shape is defined for
    r0 : float
        2-parameter resolution function slope parameter
    r1 : float
        2-parameter resolution function offset parameter
    R0 : float
        3-parameter resolution function first parameter
    m0 : float
        3-parameter resolution function second parameter
    dm : float
        3-parameter resolution function third parameter

    """

    def __init__(self, descriptor):
        """Initialize self

        Parameters
        ----------
        descriptor : TSharedMemoryDesc or TwH5Desc
            Tofwerk data descriptor (H5/ShMem)

        """

        self.desc = descriptor
        
        self._mz = self.calculate_mz()

        self.ps = None
        self.peakshapes = None

        self.r0 = None
        self.r1 = None

        self.R0 = None
        self.m0 = None
        self.dm = None

    @property
    def mz(self):
        return self._mz

    def R(self, m, r0, r1):
        """Calculate resolution at a m/z with the 2-parameter function

        The 2-parameter function is the one used by tofTools.

        Parameters
        ----------
        m : float
            m/z for which to calculate the resolution
        r0 : float
            2-parameter resolution function slope parameter
        r1 : float
            2-parameter resolution function offset parameter

        Returns
        -------
        float
            Resolution at said m/z
        """

        return m / (r0 * m + r1)

    def R_3p(self, m, R0, m0, dm):
        """Calculate resolution at a m/z with the 3-parameter function

        The 3-parameter function is the one suggested in Tofwerk documentation.

        Parameters
        ----------
        m : float
            m/z for which to calculate the resolution
        R0 : float
            3-parameter resolution function first parameter
        m0 : float
            3-parameter resolution function second parameter
        dm : float
            3-parameter resolution function third parameter

        Returns
        -------
        float
            Resolution at said m/z
        """

        return R0 - (R0 / (1 + np.exp((m - m0) / dm)))

    def load_ps(self, ps_file=None):
        """Load peakshape from a file generated by tofTools

        TODO: !!! Reconsider ps_file=None behaviour !!!

        Parameters
        ----------
        ps_file : str, optional
            Full file path to the peak shape file (.mat),
            by default None.
        """

        if ps_file is None:
            ps_file = u'ADC4_ps_new.mat'
        ps_mat = loadmat(ps_file)
        ps_struct = ps_mat['peakShape']
        ps = ps_struct['dat'][0]
        ps = ps[0]
        x = ps[:, 0]
        y = ps[:, 1]
        y = y / max(y)
        self.ps = {'x': x, 'y': y}

    def get_ps(self, ppos):
        """Get peakshape at particular position in the TOF space

        Parameters
        ----------
        ppos : float
            Peak position in TOF sample numbers. Only has effect if
            multiple peakshapes are defined along the TOF axis.

        Returns
        -------
        dict
            Dictionary with peakshape x and y vectors is returned.

        Raises
        ------
        Exception
            In case no peakshape is defined, an exception is raised.
        """

        if self.peakshapes is None and self.ps is None:
            raise Exception('Peakshape not defined')
        if self.peakshapes is None:
            return self.ps
        ps_def = np.asarray(self.peakshapes.keys())
        ps_ind = np.argmin(abs(ps_def - ppos))
        ps = self.peakshapes[ps_def[ps_ind]]
        return ps

    def fit_rfun(self):
        """Placeholder function for fitting the resolution function
        parameters.

        TODO: Implement properly
        """

        self.r0 = 0.0001034
        self.r1 = 0.002548

    def r_at(self, x, mode='R', space='mz'):
        """Calculate resolution at given m/z or sample number with the 
        2-parameter resolution function.

        Can return resolution (m/dm), peak FWHM or peak sigma in either
        tof (sample number) or m/z space.

        Parameters
        ----------
        x : float
            Peak position as either m/z or TOF sample number, specified
            by the input parameter 'space'.
        mode : str, optional
            Allowed values are 'R', 'fwhm' and 'sigma', by default 'R'.
        space : str, optional
            Allowed values are 'mz' and 'tof', by default 'mz'.

        Returns
        -------
        float
            Resolution at 'x'.

        """

        if space == 'mz':
            mz = x
        elif space == 'tof':
            mz = self.sno2mz(x)

        R = self.R(mz, self.r0, self.r1)

        fwhm = mz / R
        sigma = fwhm / (2. * np.sqrt(2. * np.log(2)))

        if mode == 'R':
            val = R
        elif mode == 'fwhm':
            val = fwhm
        elif mode == 'sigma':
            val = sigma
        # Convert to TOF space if needed
        if space == 'tof':
            if mode != 'R':
                val = (self.mz2sno(mz + 10 * val) - self.mz2sno(mz)) / 10.0
            else:
                fwhm_sno = (
                    self.mz2sno(
                        mz + 10 * fwhm) - self.mz2sno(mz)) / 10.0
                val = self.mz2sno(mz) / fwhm_sno
        return val

    def r_at_3p(self, sno, mode='R'):
        """Calculate resolution at given sample number with the 
        3-parameter resolution function.

        Can return resolution (m/dm), peak FWHM or peak sigma in 
        TOF (sample number) space.

        TODO: Should be merged with 'r_at'.

        Parameters
        ----------
        sno : float
            Peak position in sample numbers.
        mode : str, optional
            Allowed values are 'R', 'fwhm' and 'sigma', by default 'R'.

        Returns
        -------
        float
            Resolution at 'sno'.
        """

        R = self.R_3p(sno, self.R0, self.m0, self.dm)
        fwhm = sno / R
        sigma = fwhm / (2 * np.sqrt(2 * np.log(2)))
        if mode == 'R':
            return R
        elif mode == 'fwhm':
            return fwhm
        elif mode == 'sigma':
            return sigma

    def mz2sno(self, mzs, roundit=False):
        """Convert m/z to sample number.

        Conversion is done using the 'mz_mode' and 'mz_par' stored
        as attributes within the object.

        Parameters
        ----------
        mzs : float or iterable
            m/z value(s) to convert
        roundit : bool, optional
            Whether to round the sample numbers to nearest integer,
            by default False.

        Returns
        -------
        float or int or iterable
            Sample number(s) representing the 'mzs'.
        """

        if not hasattr(mzs, '__iter__'):
            mzs = [mzs]
        if roundit:
            snos = [int(round(TwMass2Tof(mz, self.desc.massCalibMode, self.desc.p)))
                    for mz in mzs
                    ]
        else:
            snos = [TwMass2Tof(mz, self.desc.massCalibMode, self.desc.p)
                    for mz in mzs
                    ]
        if len(snos) == 1:
            snos = snos[0]
        return snos

    def sno2mz(self, snos, roundit=False):
        """Convert sample number to m/z.

        Conversion is done using the 'mz_mode' and 'mz_par' stored
        as attributes within the object.

        Parameters
        ----------
        snos : float or iterable
            Sample number(s) to convert
        roundit : bool, optional
            Whether to round the m/z(s) to nearest integer,
            by default False.

        Returns
        -------
        float or int or iterable
            m/z(s) representing the 'snos'.
        """

        if not hasattr(snos, '__iter__'):
            if snos == -1:
                snos = self.desc.nbrSamples
            snos = [snos]
        if roundit:
            mzs = [int( round( TwTof2Mass(sno,
                                          self.desc.massCalibMode,
                                          self.desc.p
                                          )))
                   for sno in snos
                   ]
        else:
            mzs = [TwTof2Mass(sno, self.desc.massCalibMode, self.desc.p) 
                   for sno in snos
                   ]
        if len(mzs) == 1:
            mzs = mzs[0]
        return mzs

    def calculate_mz(self):
        return np.array([self.sno2mz(s) for s in range(self.desc.nbrSamples)],
                         dtype=np.float32
                         )