import datetime
import json
import nest_asyncio
import os
import pandas as pd
import sqlite3
import shutil

from scipy.io import loadmat

from mascope_lib.file_func import filename_to_zarr_path

from mascope_server.config import config

# patch asyncio to supported run_until_complete
# when an event loop is already running
nest_asyncio.apply()


def load_peakshape_mat(peakshape_file):
    """Load peakshape from a file generated by tofTools"""
    ps_mat = loadmat(peakshape_file)
    ps_struct = ps_mat["peakShape"]
    ps = ps_struct["dat"][0][0]
    x = ps[:, 0]
    y = ps[:, 1]
    y = y / max(y)
    return {"x": x, "y": y}


def run():
    # STEP 1 - setup new database
    old_db_path = os.path.join(config.server.database, "mascope.v6.db")
    new_db_path = os.path.join(config.server.database, "mascope.v7.db")
    shutil.copyfile(old_db_path, new_db_path)
    new_conn = sqlite3.connect(database=new_db_path)
    with new_conn:
        # # Add new instrument functions
        # peakshape_path = os.path.join(
        #     os.path.dirname(os.path.realpath(__file__)),
        #     'peakshapes'
        # )
        # instrument_function_data = []
        # # KLTOF2
        # instrument = "KLTOF2"
        # peakshape_file = os.path.join(peakshape_path, '20230118_DBrMe_new_thunings.mat')
        # peakshape = load_peakshape_mat(peakshape_file)
        # R_p1 = 0.00007847
        # R_p2 = 0.002911
        # timestamp = datetime.datetime(2023, 1, 18)
        # instrument_function_data.append((
        #     gen_id(length=32),
        #     instrument,
        #     timestamp.isoformat(),
        #     json.dumps({'x': list(peakshape['x']), 'y': list(peakshape['y'])}),
        #     json.dumps([R_p1, R_p2])
        # ))
        # instrument_function_df = pd.DataFrame.from_records(
        #     instrument_function_data,
        #     columns=(
        #         'instrument_function_id',
        #         'instrument',
        #         'datetime_utc',
        #         'peakshape',
        #         'resolution_function'
        #         )
        # )
        # instrument_function_df.to_sql(
        #     'instrument_function',
        #     new_conn,
        #     if_exists='append',
        #     index=False
        # )

        # Add isotope correlation column to match table
        new_conn.cursor().execute(
            f"""--sql
            ALTER TABLE match
            ADD match_isotope_correlation FLOAT
        """
        )

        # Add TIC column to sample_file
        new_conn.cursor().execute(
            f"""--sql
            ALTER TABLE sample_file
            ADD tic FLOAT
        """
        )

        # Delete sample file records without file
        filenames = pd.read_sql(
            """--sql
            SELECT
                filename
            FROM sample_file
            """,
            new_conn,
        ).filename.tolist()

        # Delete all peak datasets
        for filename in filenames:
            peak_areas_path = filename_to_zarr_path(filename, "peak_areas")
            peak_heights_path = filename_to_zarr_path(filename, "peak_heights")
            try:
                shutil.rmtree(peak_areas_path)
                shutil.rmtree(peak_heights_path)
            except Exception as e:
                print(e)

        # Delete all matches
        new_conn.cursor().execute(
            f"""--sql
            DELETE FROM match
        """
        )
