# -*- coding: utf-8 -*-
"""
Created on Mon Oct 31 16:32:19 2022

@author: Oskari Kausiala
"""

import numpy as np

from backend.lib.file import load_file

#%%
filename = r'C:\Data\instrument\KLTOF2\2021.08.19\KLTOF2_Comissioning-C4Q-xxx-L_2021.08.19-08h40m19s'
cache_item = load_file(filename, vars=['signal'])

mz = cache_item.mz
spec = cache_item.signal.sum(dim='time')

#%%
peakshape_file = r'C:\Users\Oskari Kausiala\Documents\Repositories\labbis\parameters\peakShapes\peakshape.mat'
p1 = 0.000125
p2 = 0.002545

from scipy.io import loadmat

def load_ps(peakshape_file):
    """Load peakshape from a file generated by tofTools
    """
    ps_mat = loadmat(peakshape_file)
    ps_struct = ps_mat['peakShape']
    ps = ps_struct['dat'][0]
    ps = ps[0]
    x = ps[:, 0]
    y = ps[:, 1]
    y = y / max(y)
    return {'x': x, 'y': y}
    
peakshape = load_ps(peakshape_file)
R = lambda m: m / (p1 * m + p2)

#%%
from backend.lib.signal.peak import fit_peaks

def fit_um(
    mz,
    spec,
    max_n_peaks=5,
    threshold=0.9
    ):
    spec_norm = np.linalg.norm(spec)
    residual = spec_norm
    for i in range(max_n_peaks):
        print(i)
        if i == 0:
            # Initialize first peak
            max_ind = np.argmax(spec)
            init_pos = [ mz[max_ind] ]
            init_hei = [ spec[max_ind] ]
            init_res = [ R(mz[max_ind]) ]
            
        fit, peaks = fit_peaks(
            mz,
            spec,
            peakshape,
            i+1,
            init_pos,
            init_hei,
            init_res,
            fit_pos=True,
            fit_hei=True,
            fit_res=False,
            dpos=0.1,
            max_iter=1000
            )
        new_residual = np.linalg.norm(fit.residual)
        # Check for add new peak condition
        if new_residual > threshold * residual:
            print("breaking")
            break
        residual = new_residual
        # Find the place to add next peak
        # Loop through already fitted peaks
        max_residual_ind = np.argmax(fit.residual)
        max_residual = fit.residual[max_residual_ind]
        max_residual_mz = mz[max_residual_ind]
        for peak_pos, peak_hei, peak_res in peaks:
            while max_residual > 0:
                hwhm = (peak_pos / peak_res) / 2
                # If the maximum of the residual is within the fitted peak, set
                # it to 0 in order to ignore it
                if (max_residual_mz > (peak_pos - hwhm)
                    and max_residual_mz < (peak_pos + hwhm)
                    ):
                    residual[max_residual_ind] = 0
                    max_residual_ind = np.argmax(fit.residual)
                    max_residual = fit.residual[max_residual_ind]
                    max_residual_mz = mz[max_residual_ind]
                else:
                    break
        # Set the position of next peak to the maximum of residual
        init_pos.append(max_residual_mz)
        init_hei.append(max_residual)
        init_res.append(R(max_residual_mz))
    return fit
    
um = 301
umz = mz.sel(mz=slice(um-.5, um+.5)).compute().values
uspec = spec.sel(mz=slice(um-.5, um+.5)).compute().values
max_n_peaks = 8

fit = fit_um(
    umz,
    uspec,
    max_n_peaks,
    threshold=0.85
    )

#%
from backend.lib.signal.peak import gen_peak
from matplotlib import pyplot as plt

plt.plot(umz, uspec)
for i in range(1, int(fit.params['npeaks'])*3, 3):
    pos, hei, _ = list(fit.params.values())[i:i+3]
    plt.plot(umz, gen_peak(umz, pos.value, hei.value, R(pos.value), peakshape))
plt.plot(umz, fit.residual)