from typing import Optional, List
from pydantic import BaseModel, Field, model_validator

# TODO_configuration Default Filter Parameters
DEFAULT_MZ_TOLERANCE = 15
DEFAULT_MIN_ISOTOPE_ABUNDANCE = 0.15
DEFAULT_ISOTOPE_RATIO_TOLERANCE = 0.15
DEFAULT_PEAK_MIN_INTENSITY = 0.0
DEFAULT_MIN_ISOTOPE_CORRELATION = 0.8
DEFAULT_PROBABLE_MATCH_THRESHOLD = 0.8
DEFAULT_POSSIBLE_MATCH_THRESHOLD = 0.7


class FilterParams(BaseModel):
    mz_tolerance: int = Field(
        DEFAULT_MZ_TOLERANCE,
        description="Tolerance for mass-to-charge ratio (m/z) error.",
    )
    isotope_ratio_tolerance: float = Field(
        DEFAULT_ISOTOPE_RATIO_TOLERANCE,
        description="Tolerance for the ratio of isotopic abundances.",
    )
    peak_min_intensity: float = Field(
        DEFAULT_PEAK_MIN_INTENSITY,
        description="Minimum peak intensity threshold for considering a match.",
    )
    min_isotope_abundance: float = Field(
        DEFAULT_MIN_ISOTOPE_ABUNDANCE,
        description="Minimum relative abundance of isotopes to consider in the match.",
    )
    min_isotope_correlation: float = Field(
        DEFAULT_MIN_ISOTOPE_CORRELATION,
        description="Minimum correlation of isotopic pattern required for a match.",
    )
    probable_match_threshold: float = Field(
        DEFAULT_PROBABLE_MATCH_THRESHOLD,
        description="Threshold score above which a match is considered probable.",
    )
    possible_match_threshold: float = Field(
        DEFAULT_POSSIBLE_MATCH_THRESHOLD,
        description="Threshold score above which a match is considered possible, but below the probable match threshold.",
    )

    @model_validator(mode="after")
    @classmethod
    def validate_thresholds(cls, values):
        probable_match_threshold = values.probable_match_threshold
        possible_match_threshold = values.possible_match_threshold

        if (
            possible_match_threshold is not None
            and probable_match_threshold is not None
        ):
            if possible_match_threshold > probable_match_threshold:
                raise ValueError(
                    "Possible match threshold must be less than or equal to probable match threshold"
                )
        return values


class MatchComputeSample(BaseModel):
    sample_item_id: str = Field(..., description="ID of the sample item")
    sample_item_name: str = Field(..., description="ID of the sample item")
    sample_batch_id: str = Field(..., description="ID of the sample batch")
    filename: str = Field(..., description="Filename of the sample item")
    instrument: str = Field(..., description="Instrument of the sample item")


class RematchBody(BaseModel):
    added_target_compound_ids: Optional[List[str]] = Field(
        None, description="List of target compound IDs to add matches for"
    )
    added_ionization_mechanism_ids: Optional[List[str]] = Field(
        None, description="List of ionization mechanism IDs to add matches for"
    )
    removed_target_compound_ids: Optional[List[str]] = Field(
        None, description="List of target compound IDs to remove matches for"
    )
    removed_ionization_mechanism_ids: Optional[List[str]] = Field(
        None, description="List of ionization mechanism IDs to remove matches for"
    )


class RematchBatchBody(RematchBody):
    sample_batch_id: Optional[str] = Field(None, description="ID of the sample batch")


class RematchBatchesBody(BaseModel):
    sample_batches: List[RematchBatchBody] = Field(
        ..., description="List of sample batches to rematch"
    )


class MatchComputeBody(BaseModel):
    added_target_compound_ids: Optional[List[str]] = Field(
        None, description="List of target compound IDs to compute matches for"
    )
    added_ionization_mechanism_ids: Optional[List[str]] = Field(
        None, description="List of ionization mechanism IDs to compute matches for"
    )


class MatchRemovePayload(BaseModel):
    removed_target_compound_ids: Optional[List[str]] = Field(
        None,
        description="Matches associated with isotopes derived from these compounds will be deleted.",
    )
    removed_ionization_mechanism_ids: Optional[List[str]] = Field(
        None,
        description="Matches associated with isotopes generated by these ionization mechanisms will be deleted",
    )


class FilterSamplePayload(BaseModel):
    sample_batch_id: Optional[str] = Field(
        None, description="Filter samples by ID of the sample batch"
    )
    sample_item_id: Optional[str] = Field(
        None, description="Filter samples by ID of the sample item"
    )

    @model_validator(mode="before")
    @classmethod
    def check_sample_item_id_or_sample_batch_id(cls, values):
        sample_item_id = values.get("sample_item_id")
        sample_batch_id = values.get("sample_batch_id")

        if sample_item_id and sample_batch_id:
            raise ValueError(
                "Specify either a sample batch ID or a sample item ID, not both."
            )
        if not sample_item_id and not sample_batch_id:
            raise ValueError(
                "Please specify at least one: a sample batch ID or a sample item ID."
            )

        return values
