from pydantic import BaseModel, Field
from typing import Optional, List


class MatchComputeSample(BaseModel):
    sample_item_id: str = Field(..., description="ID of the sample item")
    sample_item_name: str = Field(..., description="ID of the sample item")
    sample_batch_id: str = Field(..., description="ID of the sample batch")
    filename: str = Field(..., description="Filename of the sample item")
    instrument: str = Field(..., description="Instrument of the sample item")


class ProgressProperties(BaseModel):
    item_weight: Optional[float] = Field(
        None, description="Weight of the item in computation"
    )
    item_index: Optional[int] = Field(
        None, description="Index of the item being processed"
    )
    batch_index: Optional[int] = Field(
        None, description="Index of the batch being processed"
    )
    sample_batch_id: Optional[str] = Field(
        None, description="ID of the associated batch"
    )
    workspace_id: Optional[str] = Field(
        None, description="ID of the associated workspace"
    )
    total_samples: Optional[int] = Field(
        None, description="Total number of items to process"
    )
    total_batches: Optional[int] = Field(None, description="Total number of batches")
    progress_type: Optional[str] = Field(
        None,
        description="Type of progress computation ('match_batches' or 'match_item')",
    )
    sid: Optional[str] = Field(None, description="Session ID for the socket connection")
    workspace_reload: Optional[bool] = Field(
        False, description="Flag to trigger workspace reload"
    )


class RematchBody(BaseModel):
    added_target_compound_ids: Optional[List[str]] = Field(
        None, description="List of target compound IDs to add matches for"
    )
    added_ionization_mechanism_ids: Optional[List[str]] = Field(
        None, description="List of ionization mechanism IDs to add matches for"
    )
    removed_target_compound_ids: Optional[List[str]] = Field(
        None, description="List of target compound IDs to remove matches for"
    )
    removed_ionization_mechanism_ids: Optional[List[str]] = Field(
        None, description="List of ionization mechanism IDs to remove matches for"
    )
    progress_properties: Optional[ProgressProperties] = Field(
        None,
        description="Object with properties for match progress computation notification",
    )


class RematchBatchBody(RematchBody):
    sample_batch_id: Optional[str] = Field(None, description="ID of the sample batch")
    workspace_id: Optional[str] = Field(
        None, description="ID of the workspace associated with the sample batch"
    )


class RematchBatchesBody(BaseModel):
    sample_batches: List[RematchBatchBody] = Field(
        ..., description="List of sample batches to rematch"
    )


class MatchComputeBody(BaseModel):
    added_target_compound_ids: Optional[List[str]] = Field(
        None, description="List of target compound IDs to compute matches for"
    )
    added_ionization_mechanism_ids: Optional[List[str]] = Field(
        None, description="List of ionization mechanism IDs to compute matches for"
    )


class MatchRemovePayload(BaseModel):
    removed_target_compound_ids: Optional[List[str]] = Field(
        None,
        description="Matches associated with isotopes derived from these compounds will be deleted.",
    )
    removed_ionization_mechanism_ids: Optional[List[str]] = Field(
        None,
        description="Matches associated with isotopes generated by these ionization mechanisms will be deleted",
    )
    independent_transaction: Optional[bool] = Field(
        default=True,
        description="Flag indicating whether the match removal is an independent transaction and if the operation should emit a reload event for the sample batch.",
    )
