# -*- mode: ruby -*-
# vi: set ft=ruby :

##Vagrant takes care of VBGuestAdditions
#vagrant plugin install vagrant-vbguest
#vagrant up      

Vagrant.configure("2") do |config|
# #  required_plugins = %w( vagrant-vbguest vagrant-disksize vagrant-reload )
  required_plugins = %w( vagrant-vbguest vagrant-env )
#  _retry = false
  required_plugins.each do |plugin|
    unless Vagrant.has_plugin? plugin
      system "vagrant plugin install #{plugin}"
#      _retry=true
    end
  end

  # config.vm.box = "fasmat/ubuntu2004-desktop"
  config.vm.box = "ubuntu/focal64"
  config.env.enable

  # expose mascope frontend http and https ports;
  MASCOPE_HTTP = ENV['MASCOPE_PUBLIC_PORT']
  MASCOPE_HTTPS = 443
  MASCOPE_API = ENV['MASCOPE_PUBLIC_API_PORT']
  MASCOPE_PRIVATE_DATADIR = ENV['MASCOPE_PRIVATE_DATADIR']
  MASCOPE_PRIVATE_CONVERTER_DIR = ENV['MASCOPE_PRIVATE_CONVERTER_DIR']
  MASCOPE_PRIVATE_DOWNLOADER_DIR = ENV['MASCOPE_PRIVATE_DOWNLOADER_DIR']
  MASCOPE_PRIVATE_LOG_DIR = ENV['MASCOPE_PRIVATE_LOG_DIR']

  # for ssh access to the image, use port 2201: e.g. ssh vagrant@localhost -p 2201
  # vagrant itself uses redirection 22->2222, which can be also used if no conflicts
  config.vm.network "forwarded_port", guest: 22, host: 2201, id: "dev_ssh"
  config.vm.network "forwarded_port", guest: MASCOPE_HTTP, host: MASCOPE_HTTP, id: "mascope-http"
  config.vm.network "forwarded_port", guest: MASCOPE_API, host: MASCOPE_API, id: "mascope-api"
  config.vm.network "forwarded_port", guest: MASCOPE_HTTPS, host: MASCOPE_HTTPS, id: "mascope-https"
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../..", "/vagrant"
  # for production
  config.vm.synced_folder "D:/Data", MASCOPE_PRIVATE_DATADIR
  config.vm.synced_folder "D:/to_mascope", MASCOPE_PRIVATE_CONVERTER_DIR
  config.vm.synced_folder "V:/Data/to_mascope", MASCOPE_PRIVATE_DOWNLOADER_DIR
  config.vm.synced_folder "../../../log", MASCOPE_PRIVATE_LOG_DIR
  # for local tests
  # config.vm.synced_folder "../../../data", MASCOPE_PRIVATE_DATADIR
  # config.vm.synced_folder "../../../to_mascope", MASCOPE_PRIVATE_CONVERTER_DIR
  # config.vm.synced_folder "../../../from_instrument", MASCOPE_PRIVATE_DOWNLOADER_DIR
  # config.vm.synced_folder "../../../log", MASCOPE_PRIVATE_LOG_DIR

  config.vm.hostname = "mascope"
  
  config.vm.provider :virtualbox do |vb|
    vb.name = "mascope"
    vb.gui = true
    # for production
    vb.memory = "8192"
    # for local tests
    # vb.memory = "2048"
    vb.cpus = 2
    # to enable proper links functionality in Windows shared folders
    vb.customize ["setextradata", :id,
                  "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant",
                  "1"] 
    # vb.customize ["storageattach", :id, 
    #               "--storagectl", "IDE", 
    #               "--port", "0", "--device", "1", 
    #               "--type", "dvddrive", 
    #               "--medium", "emptydrive"]    
  end
 
  config.vm.provision "shell", inline: "cd /vagrant/scripts/deploy/staging.linux.vbox && ./pre_provision.sh", privileged: false
  config.vm.provision "shell", inline: "cd /vagrant/scripts/deploy/staging.linux.vbox && ./provision_ssh_access.sh", privileged: false
  config.vm.provision "shell", inline: "cd /vagrant/scripts/deploy/staging.linux.vbox && ./provision_box.sh", privileged: false
  config.vm.provision "shell", run: 'always', inline: "sudo systemctl restart mascope", privileged: false
  
end
