# -*- mode: ruby -*-
# vi: set ft=ruby :

##Vagrant takes care of VBGuestAdditions
#vagrant plugin install vagrant-vbguest
#vagrant up      

Vagrant.configure("2") do |config|
  required_plugins = %w( vagrant-vbguest vagrant-env )
#  _retry = false
  required_plugins.each do |plugin|
    unless Vagrant.has_plugin? plugin
      system "vagrant plugin install #{plugin}"
#      _retry=true
    end
  end
  config.vbguest.auto_update = false
  
  # # the values below are handled by importer
  # config.vm.box = "ubuntu/jammy64"
  # config.vm.synced_folder ".", "/vagrant", disabled: true
  # config.vm.synced_folder "../../..", "/vagrant"

  # envs are loaded by importer
  # config.env.enable
  # Dotenv.overload('.env')
  # Dotenv.overload('.debug_env')

  MASCOPE_HTTP = ENV['MASCOPE_PUBLIC_PORT']
  MASCOPE_HTTPS = 443
  MASCOPE_API = ENV['MASCOPE_PUBLIC_API_PORT']
  MASCOPE_PRIVATE_DATADIR = ENV['MASCOPE_PRIVATE_DATADIR']
  MASCOPE_PRIVATE_CONVERTER_DIR = ENV['MASCOPE_PRIVATE_CONVERTER_DIR']
  MASCOPE_PRIVATE_DOWNLOADER_DIR = ENV['MASCOPE_PRIVATE_DOWNLOADER_DIR']
  MASCOPE_PRIVATE_LOG_DIR = ENV['MASCOPE_PRIVATE_LOG_DIR']

  VAGRANT_HOST_DATADIR = ENV['VAGRANT_HOST_DATADIR'] || "D:/Data"
  VAGRANT_HOST_CONVERTER_DIR = ENV['VAGRANT_HOST_CONVERTER_DIR'] || "D:/to_mascope"
  VAGRANT_HOST_DOWNLOADER_DIR = ENV['VAGRANT_HOST_DOWNLOADER_DIR'] || "V:/Data/to_mascope"
  VAGRANT_HOST_LOG_DIR = ENV['VAGRANT_HOST_LOG_DIR'] || "../../../../log"
  VAGRANT_VB_MEMORY = ENV['VAGRANT_VB_MEMORY'] || "8192"
  
  # for ssh access to the image, use port 2201: e.g. ssh vagrant@localhost -p 2201
  # vagrant itself uses redirection 22->2222, which can be also used if no conflicts;
  # expose mascope frontend and api ports;
  config.vm.network "forwarded_port", guest: 22, host: 2201, id: "dev_ssh"
  config.vm.network "forwarded_port", guest: MASCOPE_HTTP, host: MASCOPE_HTTP, id: "mascope-http"
  config.vm.network "forwarded_port", guest: MASCOPE_API, host: MASCOPE_API, id: "mascope-api"
  config.vm.network "forwarded_port", guest: MASCOPE_HTTPS, host: MASCOPE_HTTPS, id: "mascope-https"

  config.vm.synced_folder VAGRANT_HOST_DATADIR, MASCOPE_PRIVATE_DATADIR
  config.vm.synced_folder VAGRANT_HOST_CONVERTER_DIR, MASCOPE_PRIVATE_CONVERTER_DIR
  config.vm.synced_folder VAGRANT_HOST_DOWNLOADER_DIR, MASCOPE_PRIVATE_DOWNLOADER_DIR
  config.vm.synced_folder VAGRANT_HOST_LOG_DIR, MASCOPE_PRIVATE_LOG_DIR

  config.vm.hostname = "mascope-" + ENV['COMPUTERNAME']
  
  config.vm.provider :virtualbox do |vb|
    vb.name = config.vm.hostname
    vb.gui = true
    vb.memory = VAGRANT_VB_MEMORY
    vb.cpus = 2
    # to enable proper links functionality in Windows shared folders
    vb.customize ["setextradata", :id,
                  "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant",
                  "1"] 
    # vb.customize ["storageattach", :id, 
    #               "--storagectl", "IDE", 
    #               "--port", "0", "--device", "1", 
    #               "--type", "dvddrive", 
    #               "--medium", "emptydrive"]    
  end
 
  config.vm.provision "shell", inline: "cd /vagrant/scripts/deploy/staging.linux.vbox && ./pre_provision.sh", privileged: false
  config.vm.provision "shell", inline: "cd /vagrant/scripts/deploy/staging.linux.vbox && ./provision_ssh_access.sh", privileged: false
  config.vm.provision "shell", inline: "cd /vagrant/scripts/deploy/staging.linux.vbox && ./provision_box.sh", privileged: false
  # config.vm.provision "shell", run: 'always', inline: "sudo systemctl restart mascope", privileged: false
  
end
