session_name: mascope
windows:
  - window_name: server
    layout: even-horizontal
    panes:
      - init server
  - window_name: services
    layout: main-horizontal
    panes:
      - init router --url 0.0.0.0
      - init file-io-service --ns TofDaq
      - init file-streaming-service --config=./backend/service/file_streamer_config/h5_localstore.yaml  --transit
      - init file-streaming-service --config=./backend/service/file_streamer_config/raw_localstore.yaml  --transit