"""
Integration tests for Bearer-token access to the TUS upload endpoint.

Agents (File Agent) authenticate with a service access token. The TUS
routes are generated by tuspyserver, so they cannot take the @api_route
decorator; sample_files_routes stamps their endpoints `token_access`
instead. These tests pin that stamp down: a file-agent token must pass
the auth layer on upload creation and chunk transfer, while the
service-name check and anonymous rejection keep working.

The upload is never completed here (chunks stop short of Upload-Length),
so the file-processing pipeline behind the completion hook stays out of
scope.
"""

import base64

import pytest
import pytest_asyncio
from httpx import ASGITransport, AsyncClient
from sqlalchemy import delete

from mascope_backend.app.fast import fast
from mascope_backend.db import AccessToken


TUS_URL = "/api/sample/files/upload/tus/"


def _b64(value: str) -> str:
    return base64.b64encode(value.encode()).decode()


CREATE_HEADERS = {
    "Tus-Resumable": "1.0.0",
    "Upload-Length": "8",
    "Upload-Metadata": (
        f"filename {_b64('orbi1_20260801_pos.raw')},"
        f"filetype {_b64('application/octet-stream')}"
    ),
}


@pytest_asyncio.fixture
async def file_agent_token(async_session_factory, test_users):
    """A real file-agent access token row for the editor test user."""
    token = "tus-token-access-integration-test".ljust(43, "x")
    async with async_session_factory() as session:
        session.add(
            AccessToken(
                token=token,
                user_id=test_users["editor"].id,
                service_name="file-agent",
            )
        )
        await session.commit()
    yield token
    async with async_session_factory() as session:
        await session.execute(delete(AccessToken).where(AccessToken.token == token))
        await session.commit()


def _client(headers: dict | None = None) -> AsyncClient:
    return AsyncClient(
        transport=ASGITransport(app=fast), base_url="http://test", headers=headers
    )


@pytest.mark.asyncio
async def test_agent_token_can_create_and_patch_upload(file_agent_token):
    headers = {
        "Authorization": f"Bearer {file_agent_token}",
        "X-Service-Name": "file-agent",
    }
    async with _client(headers) as client:
        resp = await client.post(TUS_URL, headers=CREATE_HEADERS)
        assert resp.status_code == 201, resp.text
        upload_id = resp.headers["location"].rstrip("/").rsplit("/", 1)[-1]
        assert upload_id

        # Send half of Upload-Length: the chunk is accepted and the
        # upload stays open (no completion pipeline).
        resp = await client.patch(
            f"{TUS_URL}{upload_id}",
            content=b"half",
            headers={
                "Tus-Resumable": "1.0.0",
                "Upload-Offset": "0",
                "Content-Type": "application/offset+octet-stream",
            },
        )
        assert resp.status_code == 204, resp.text
        assert resp.headers["upload-offset"] == "4"


@pytest.mark.asyncio
async def test_token_with_mismatched_service_name_is_rejected(file_agent_token):
    headers = {
        "Authorization": f"Bearer {file_agent_token}",
        "X-Service-Name": "mascope_sdk",  # token is for file-agent
    }
    async with _client(headers) as client:
        resp = await client.post(TUS_URL, headers=CREATE_HEADERS)
    assert resp.status_code == 401


@pytest.mark.asyncio
async def test_anonymous_upload_creation_is_rejected():
    async with _client() as client:
        resp = await client.post(TUS_URL, headers=CREATE_HEADERS)
    assert resp.status_code == 401
