# -*- mode: ruby -*-
# vi: set ft=ruby :

##Vagrant takes care of VBGuestAdditions
#vagrant plugin install vagrant-vbguest
#vagrant up      

# expose karsa-router-service port 5010; 
KARSA_ROUTER_PORT = "5010"
 
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

#  required_plugins = %w( vagrant-vbguest vagrant-disksize vagrant-reload )
  required_plugins = %w( vagrant-vbguest )
#  _retry = false
  required_plugins.each do |plugin|
    unless Vagrant.has_plugin? plugin
      system "vagrant plugin install #{plugin}"
#      _retry=true
    end
  end

  # for ssh access to the image, use port 2201: e.g. ssh vagrant@localhost -p 2201
  # vagrant itself uses redirection 22->2222, which can be also used if no conflicts
  config.vm.network "forwarded_port", guest: 22, host: 2201, id: "dev_ssh"
  config.vm.network "forwarded_port", guest: KARSA_ROUTER_PORT, host: KARSA_ROUTER_PORT, id: "karsa-router-service"
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../..", "/vagrant"

  config.vm.hostname = "router-box"
  
  config.vm.provider :virtualbox do |vb|
    vb.name = "router-box"
    vb.gui = true
    vb.memory = "2048"
    vb.cpus = 2
    # to enable proper links functionality in Windows shared folders
    vb.customize ["setextradata", :id,
                  "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant",
                  "1"] 
    vb.customize ["storageattach", :id, 
                  "--storagectl", "IDE", 
                  "--port", "0", "--device", "1", 
                  "--type", "dvddrive", 
                  "--medium", "emptydrive"]    
  end
 
  config.vm.provision "shell", inline: "cd /vagrant/vbox/router && ./pre_provision.sh", privileged: false
  config.vm.provision "shell", inline: "cd /vagrant/vbox/router && ./provision_ssh_access.sh", privileged: false
  config.vm.provision "shell", inline: "cd /vagrant/vbox/router && ./provision_router_box.sh", privileged: false
  # config.vm.provision "shell", inline: "cd /vagrant/vbox/router && ./router_setup.sh", privileged: false
  config.vm.provision "shell", run: 'always', inline: '/bin/bash -c "echo ======== & echo Now run karsa-router-service from the image console & echo ========"', privileged: false
  # config.vm.provision "shell", run: 'always', inline: "cd /vagrant && karsa-router-service", privileged: false
  
end
