from pydantic import BaseModel, Field
from typing import Optional, List


class MatchComputeSample(BaseModel):
    sample_item_id: str = Field(..., description="ID of the sample item")
    sample_item_name: str = Field(..., description="ID of the sample item")
    sample_batch_id: str = Field(..., description="ID of the sample batch")
    filename: str = Field(..., description="Filename of the sample item")
    instrument: str = Field(..., description="Instrument of the sample item")


class RematchBody(BaseModel):
    added_target_compound_ids: Optional[List[str]] = Field(
        None, description="List of target compound IDs to add matches for"
    )
    added_ionization_mechanism_ids: Optional[List[str]] = Field(
        None, description="List of ionization mechanism IDs to add matches for"
    )
    removed_target_compound_ids: Optional[List[str]] = Field(
        None, description="List of target compound IDs to remove matches for"
    )
    removed_ionization_mechanism_ids: Optional[List[str]] = Field(
        None, description="List of ionization mechanism IDs to remove matches for"
    )


class RematchBatchBody(RematchBody):
    sample_batch_id: Optional[str] = Field(None, description="ID of the sample batch")


class RematchBatchesBody(BaseModel):
    sample_batches: List[RematchBatchBody] = Field(
        ..., description="List of sample batches to rematch"
    )


class MatchComputeBody(BaseModel):
    added_target_compound_ids: Optional[List[str]] = Field(
        None, description="List of target compound IDs to compute matches for"
    )
    added_ionization_mechanism_ids: Optional[List[str]] = Field(
        None, description="List of ionization mechanism IDs to compute matches for"
    )


class MatchRemovePayload(BaseModel):
    removed_target_compound_ids: Optional[List[str]] = Field(
        None,
        description="Matches associated with isotopes derived from these compounds will be deleted.",
    )
    removed_ionization_mechanism_ids: Optional[List[str]] = Field(
        None,
        description="Matches associated with isotopes generated by these ionization mechanisms will be deleted",
    )
