# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/jammy64"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../../..", "/vagrant"

  Dotenv.overload('../.env')
  Dotenv.overload('../.debug_env')

end

eval File.read('../Vagrantfile')
