from enum import Enum


class ErrorCode(Enum):
    """Reply message error codes

    Refer to interface specifications.
    """
    KRS_SUCCESS	= 0x00
    KRS_ERR_UNKOWN_COMMAND = 0x01
    KRS_ERR_INVALID_PARAM = 0x02
    KRS_ERR_INVALID_LENGTH = 0x03
    KRS_ERR_INTERNAL = 0x04

    KRS_ERR_NODE_NOT_SUPPORTED = 0x10
    KRS_ERR_NODE_NOT_FOUND = 0x11
    KRS_ERR_INVALID_NODE_TYPE = 0x12

    KRS_ERR_CAN_TX = 0x20
    KRS_ERR_CAN_RX = 0x21
    KRS_ERR_UNSUPPORTED_DATASIZE = 0x22

    KRS_ERR_MEAS_NOT_ONGOING = 0x30
    KRS_ERR_MFC_INVALID_OBJ_SUB_PAIR = 0x31
    KRS_ERR_MFC_NO_MEAS_ENTRY = 0x32

    KRS_ERR_MFC_MEAS_START = 0x40
    KRS_ERR_AI_MEAS_START_CH_1_4 = 0x41
    KRS_ERR_AI_MEAS_START_CH_5_6 = 0x42
    KRS_ERR_DIO_MEAS_START = 0x43 # typo in IF specs doc?
    # //