# -*- mode: ruby -*-
# vi: set ft=ruby :

##Vagrant takes care of VBGuestAdditions
#vagrant plugin install vagrant-vbguest
#vagrant up      

# expose mascope frontend http and https ports; 
MASCOPE_HTTP = 80
MASCOPE_HTTPS = 443
MASCOPE_API = 8091
 
Vagrant.configure("2") do |config|

  # config.vm.box = "fasmat/ubuntu2004-desktop"
  config.vm.box = "ubuntu/focal64"

# #  required_plugins = %w( vagrant-vbguest vagrant-disksize vagrant-reload )
  required_plugins = %w( vagrant-vbguest )
#  _retry = false
  required_plugins.each do |plugin|
    unless Vagrant.has_plugin? plugin
      system "vagrant plugin install #{plugin}"
#      _retry=true
    end
  end

  # for ssh access to the image, use port 2201: e.g. ssh vagrant@localhost -p 2201
  # vagrant itself uses redirection 22->2222, which can be also used if no conflicts
  config.vm.network "forwarded_port", guest: 22, host: 2201, id: "dev_ssh"
  config.vm.network "forwarded_port", guest: MASCOPE_HTTP, host: MASCOPE_HTTP, id: "mascope-http"
  config.vm.network "forwarded_port", guest: MASCOPE_API, host: MASCOPE_API, id: "mascope-api"
  config.vm.network "forwarded_port", guest: MASCOPE_HTTPS, host: MASCOPE_HTTPS, id: "mascope-https"
  
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../..", "/vagrant"
  config.vm.synced_folder "D:/Data", "/mascope_data"

  config.vm.hostname = "mascope"
  
  config.vm.provider :virtualbox do |vb|
    vb.name = "mascope"
    vb.gui = true
    vb.memory = "4096"
    vb.cpus = 2
    # to enable proper links functionality in Windows shared folders
    vb.customize ["setextradata", :id,
                  "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant",
                  "1"] 
    # vb.customize ["storageattach", :id, 
    #               "--storagectl", "IDE", 
    #               "--port", "0", "--device", "1", 
    #               "--type", "dvddrive", 
    #               "--medium", "emptydrive"]    
  end
 
  config.vm.provision "shell", inline: "cd /vagrant/deploy/production.linux.vbox && ./pre_provision.sh", privileged: false
  config.vm.provision "shell", inline: "cd /vagrant/deploy/production.linux.vbox && ./provision_ssh_access.sh", privileged: false
  config.vm.provision "shell", inline: "cd /vagrant/deploy/production.linux.vbox && ./provision_box.sh", privileged: false
  config.vm.provision "shell", run: 'always', inline: "sudo systemctl restart mascope", privileged: false
  # config.vm.provision "shell", run: 'always', inline: '/bin/bash -c "echo ========; echo Now run karsa-router-service --url=0.0.0.0 --port=#{MASCOPE_HTTP} in a terminal; echo ========"', privileged: false
  # config.vm.provision "shell", run: 'always', inline: "cd /vagrant && karsa-router-service --url=0.0.0.0 --port=#{MASCOPE_HTTP}", privileged: false
  
end
