# -*- coding: utf-8 -*-
"""
Created on Wed Apr 03 09:19:39 2019

@author: Oskari Kausiala
"""

import numpy as np
import pandas as pd

import sqlite3


from collections import namedtuple

# # TODO: remove kchem import from here, since every time kutil is loaded, it expensively
# # loads ctyped API from external karsatof.TwTool, which is mostly not needed.
# from .chem import get_exact_mass, get_exact_isotope_masses


def get_peaklist_all_tables_rows(peaklist_path, tables):
    """Read peaklist SQLite database

    NOTE: !!! Not sure how this is supposed to be used !!!

    Parameters
    ----------
    peaklist_path : str
        Full file path
    tables : list
        db tables to fetch

    Returns
    -------
    dict
        Database contents
    """

    try:
        conn = sqlite3.connect(peaklist_path)
    except:
        return {}
    c = conn.cursor()
    all_rows = {}

    for table in tables:
        columns = c.execute("SELECT * FROM {}".format(table)).description
        all_rows[table] = []

        for row in c.fetchall():
            dict_ = {}
            for (index, value) in enumerate(row):
                dict_[columns[index][0]] = value
            all_rows[table].append(dict_)

    conn.close()
    return all_rows

# # TODO: remove update_peaklist_db_peaks_table from kutils, since it needs expensive
# # ctyped API from external karsatof.TwTool, while it's mostly not needed
# def update_peaklist_db_peaks_table(peaklist_path, table, task, values):
#     """Add data to peaklist SQLite database

#     NOTE: !!! Not sure how this is supposed to be used !!!

#     Parameters
#     ----------
#     peaklist_path : str
#         Full file path
#     table : str
#         Table to modify, only used if 'task' is either 'edit' or 'delete'.
#     task : str
#         Task to perform to selected table, allowed values:
#         'create', 'edit' or 'delete'
#     values : dict
#         Not sure what this should be ???

#     Returns
#     -------
#     None
#     """

#     if peaklist_path is None or table is None or task is None or values is None:
#         return
#     else:
#         try:
#             conn = sqlite3.connect(peaklist_path)
#         except:
#             return

#         c = conn.cursor()
#         query = ""

#         if task == "create":
#             columns = '`, `'.join(list(values.get("db_row_pairs").keys()))
#             query_values = "', '".join(
#                 list(values.get("db_row_pairs").values()))
#             molComp = values.get("db_row_pairs").get("molComp")
#             mass = get_exact_mass(molComp)[0]
#             query = """ INSERT INTO {} (`pId`, `mass`, `{}`)
#                         VALUES ((SELECT MAX(pId) FROM peaks) + 1, {},  '{}') """.format(
#                         'peaks', columns, str(mass), query_values)
#             c.execute(query)
#             last_inserted_id = c.lastrowid
#             conn.commit()

#             # isotope table needs inserted values generated by get_exact_isotope_masses
#             isotope_values = get_exact_isotope_masses(molComp)
#             try:
#                 for i in range(0, len(isotope_values[0])):
#                     q = """INSERT INTO isotopes (`pId`, `mass`, `abundance`) VALUES ({}, {}, {})""".format(
#                         last_inserted_id, str(isotope_values[0][i]),
#                         str(isotope_values[1][i]))
#                     c.execute(q)
#                     conn.commit()
#             except:
#                 # rollback if first qury succedded but second query failed..
#                 if last_inserted_id is not None:
#                     c.execute(
#                         """ DELETE FROM isotopes WHERE pId = (
#                         SELECT MAX(pId) FROM peaks) """
#                     )
#                     conn.commit()
#         else:
#             primary_column_id = values.get("primary_column_id")
#             primary_column_value = "{}{}{}".format(
#                     "'",
#                     values.get("primary_column_value"),
#                     "'"
#                 ) if values.get("primary_column_value"
#                     ) is not None else (
#                         'NULL OR {}=""'.format(primary_column_id)
#                     )
#             operator = "=" if values.get(
#                 "primary_column_value") is not None else " is "

#         if task == "edit":
#             set_query_part = (",").join([
#                 key + "='" + str(value) + "'"
#                 for key, value in values.get("db_row_pairs").items()
#             ])
#             query = "UPDATE {} SET {} WHERE {} {} {}".format(
#                 table, set_query_part, primary_column_id, operator,
#                 primary_column_value)
#             c.execute(query)
#             conn.commit()

#         if task == "delete":
#             query = "DELETE FROM {} WHERE {} {} {}".format(
#                 table, primary_column_id, operator, primary_column_value)
#             c.execute(query)
#             conn.commit()

#             # now cleanup the table where pId is not equal to pId In Isotopes,
#             # also removes invalid rows in isotope table
#             query = """DELETE FROM isotopes
#                         WHERE isotopes.pId not IN ( SELECT DISTINCT(pId) FROM peaks) """
#             c.execute(query)
#             conn.commit()

#         conn.close()


def read_peaklist(filename, min_iso_abu=0.4):
    """Read peaklist SQLite database, generated in tofTools

    Parameters
    ----------
    filename : str
        Full file path
    min_iso_abu : float, optional
        For each compound in the db, all isotopes with relative abundance
        greater than this will be returned, by default 0.4

    Returns
    -------
    dict
        Dictionary with contents of the peaklist db
    """

    # Set up a named tuple
    Peak = namedtuple('Peak', 'pId, ref, molComp')
    # Read database file
    try:
        conn = sqlite3.connect(filename)
    except:
        return {}
    c = conn.cursor()
    c.execute("SELECT pId, reference, molComp FROM peaks")
    # Peaks
    peaks = []
    for pk in map(Peak._make, c.fetchall()):
        peaks.append(pk)
    # Isotopes
    c.execute("SELECT pId, mass, abundance FROM isotopes")
    isotopes = c.fetchall()
    # Make peak dict
    peaklist = {}
    for peak in peaks:
        if peak[0] not in peaklist:
            peaklist[peak[0]] = {}
        peaklist[peak[0]]['molComp'] = peak[2]
        peaklist[peak[0]]['ref'] = peak[1]
    # Make isotope dict
    isotopelist = {}
    for iso in isotopes:
        if iso[2] < min_iso_abu:
            continue
        if iso[0] not in isotopelist:
            isotopelist[iso[0]] = {}
            isotopelist[iso[0]]['abundance'] = []
            isotopelist[iso[0]]['mass'] = []
        isotopelist[iso[0]]['abundance'].append(iso[2])
        isotopelist[iso[0]]['mass'].append(iso[1])
    # Merge peaks and isotopes
    pl = {}
    for pId, vals in peaklist.items():
        if pId in isotopelist.keys():
            if len(vals['ref']) > 0:
                key = vals['ref']
            else:
                key = peaklist[pId]['molComp']
            pl[key] = isotopelist[pId]
            pl[key]['molComp'] = peaklist[pId]['molComp']
    try:
        # Identification parameters
        c.execute("SELECT reference, threshold, mzErrTol, \
                  isoAbuTol, isoPearR FROM idparams")
        id_params = c.fetchall()
        # Add id parameters to peaklsit dict
        for par in id_params:
            if par[0] in pl.keys():
                pl[par[0]]['idPar'] = (par[1], par[2], par[3], par[4])
    except:
        for pId in pl.keys():
            pl[pId]['idPar'] = (0, 0, 0, 0)
    conn.close()
    return pl


def peaklist_to_df(peaklist):
    """Convert peaklist dictionary to a DataFrame

    Parameters
    ----------
    peaklist : dict
        Peaklist dictionary as returned by the function 'read_peaklist'

    Returns
    -------
    DataFrame
        Peaklist as a DataFrame
    """

    df = pd.DataFrame()
    df['molComp'] = []
    df['mass'] = []
    df['mass'] = df['mass'].astype(object)
    df['abundance'] = []
    df['abundance'] = df['abundance'].astype(object)

    keys = peaklist.keys()
    molComps = [vals['molComp'] for pId, vals in peaklist.items()]
    masses = [np.array(vals['mass']) for pId, vals in peaklist.items()]
    abus = [np.array(vals['abundance']) for pId, vals in peaklist.items()]
    idpar = [np.array(vals['idPar']) for pId, vals in peaklist.items()]

    df['molComp'] = molComps
    df['mass'] = masses
    df['abundance'] = abus
    df['idPar'] = idpar
    df.index = keys
    return df


def write_detection_par_to_pl(filename, peak_df):
    """Write detection parameters to peaklist SQLite database

    Parameters
    ----------
    filename : str
        Full file path
    peak_df : DataFrame
        Peaklist DataFrame (with the detection parameters)

    Raises
    ------
    Warning
        Warning is raised if database could not be modified
    """

    try:
        conn = sqlite3.connect(filename)
    except:
        raise Warning('Writing to peaklist \
                      database %s failed!' % filename)
    c = conn.cursor()
    # Check if idparams table exists
    #get the count of tables with the name
    c.execute(''' SELECT count(name) FROM sqlite_master 
              WHERE type='table' AND name='idparams' ''')
    if c.fetchone()[0] != 1:
        # Does not exist, create table
        c.execute('''CREATE TABLE idparams
          (reference text, mzErrTol real, \
          isoAbuTol real, isoPearR real)''')

    for pref, p in peak_df.iterrows():
        c.execute(
            '''UPDATE idparams
                  SET threshold = ?,
                      mzErrTol = ?,
                      isoAbuTol = ?,
                      isoPearR = ?
                  WHERE reference = ?''',
            (p['idPar'][0], p['idPar'][1], p['idPar'][2], p['idPar'][3], pref))
    # Save (commit) the changes
    conn.commit()
    conn.close()



                

