"""
Migration script for v37: Ionization Mode System Implementation.

This migration implements the ionization mode system by extracting and consolidating
ionization parameters from sample_batch.build_params into a dedicated ionization_mode
table with proper relationships and foreign key constraints.
"""

import asyncio
import json
import os
import shutil
from typing import Any

from sqlalchemy import text, update

from mascope_backend.api.controllers.sample.items.sample_items_controller import (
    get_sample_items,
)
from mascope_backend.db import (
    Base,
    IonizationMode,
    Sample,
    SampleItem,
    async_session,
    configure_database_engine,
)
from mascope_backend.db.id import gen_id
from mascope_backend.db.ops.backup import create_db_backup
from mascope_backend.runtime import runtime


async def collect_unique_build_params() -> tuple[list[dict[str, Any]], dict[str, Any]]:
    """
    Collect unique build params from all sample batches and create ionization modes.

    :return: Tuple of (unique_ionization_modes, batch_to_mode_mapping)
    """

    def normalize_ion_mechanisms(ion_mechanisms: list[str]) -> list[str]:
        """
        Normalize ion mechanisms list by sorting to ensure consistent ordering.

        :param ion_mechanisms: List of ion mechanism IDs
        :return: Sorted list of ion mechanism IDs
        """
        if not ion_mechanisms:
            return []
        return sorted(ion_mechanisms)

    def create_ionization_mode_name(index: int, polarity: str) -> str:
        """
        Generate a name for the ionization mode based on its components.

        :param index: Index number for uniqueness
        :param polarity: Polarity (+ or -)
        :return: Generated name
        """

        return f"AutoGenerated{index}{polarity}"

    # Step 1: Fetch all sample batches
    async with async_session() as session:
        result = await session.execute(
            text("SELECT sample_batch_id, build_params FROM sample_batch")
        )
        sample_batches = result.mappings().all()

    runtime.logger.info(f"Found {len(sample_batches)} sample batches to process")

    # Step 2: Collect unique combinations
    unique_combinations = {}  # Key: (normalized_mechanisms_tuple, calibration_collection, polarity) -> mode_data
    batch_to_combinations = {}  # batch_id -> combination_keys

    for batch in sample_batches:
        batch_id = batch["sample_batch_id"]
        build_params = json.loads(batch["build_params"])

        # Extract ion_mechanisms and calibration_collection
        ion_mechanisms = build_params.get("ion_mechanisms", [])
        calibration_collection = build_params.get("calibration_collection")

        # Organize ionization mechanisms by polarity
        ionization_mechanisms_by_polarity = {"+": [], "-": []}
        for mech_id in ion_mechanisms:
            async with async_session() as session:
                result = await session.execute(
                    text(
                        "SELECT ionization_mechanism_id, ionization_mechanism_polarity FROM ionization_mechanism WHERE ionization_mechanism_id = :mech_id"
                    ),
                    {"mech_id": mech_id},
                )
                ion_mech = result.mappings().first()
            ionization_mechanisms_by_polarity[
                ion_mech["ionization_mechanism_polarity"]
            ].append(ion_mech["ionization_mechanism_id"])

        for polarity in ("+", "-"):
            if len(ionization_mechanisms_by_polarity[polarity]) == 0:
                continue
            # Normalize the ion mechanisms (sort for consistency)
            normalized_mechanisms = normalize_ion_mechanisms(
                ionization_mechanisms_by_polarity[polarity]
            )

            # Create combination key
            combination_key = (
                tuple(normalized_mechanisms),
                calibration_collection,
                polarity,
            )

            # Store the mapping for this batch
            if batch_id not in batch_to_combinations:
                batch_to_combinations[batch_id] = []

            batch_to_combinations[batch_id].append(combination_key)

            # If this combination is new, store it
            if combination_key not in unique_combinations:
                ionization_mode_id = gen_id(16)
                ionization_mode_name = create_ionization_mode_name(
                    len(unique_combinations) + 1, polarity
                )

                unique_combinations[combination_key] = {
                    "ionization_mode_id": ionization_mode_id,
                    "ionization_mode_name": ionization_mode_name,
                    "ionization_mode_token": None,  # Leave empty as requested
                    "ionization_mode_polarity": polarity,
                    "ionization_mechanism_ids": normalized_mechanisms,
                    "calibration_collection_id": calibration_collection,
                    "diagnostic_collection_id": None,  # Not specified in build_params
                }

    runtime.logger.info(
        f"Found {len(unique_combinations)} unique ionization mode combinations"
    )

    return unique_combinations, batch_to_combinations


async def create_ionization_mode_table() -> None:
    """
    Create the ionization_mode table using SQLAlchemy model.
    """
    runtime.logger.info("Creating ionization_mode table...")

    async with async_session() as session:
        connection = await session.connection()

        # Create only the new ionization_mode table
        # metadata.create_all() will skip existing tables
        await connection.run_sync(Base.metadata.create_all)

        await session.commit()

    runtime.logger.info("Ionization_mode table created successfully")


async def populate_ionization_modes(unique_modes: list[dict[str, Any]]) -> None:
    """
    Populate the ionization_mode table with unique modes.

    :param unique_modes: List of ionization mode data dictionaries
    """
    async with async_session() as session:
        for mode_data in unique_modes:
            ionization_mode = IonizationMode(**mode_data)
            session.add(ionization_mode)

        await session.commit()
        runtime.logger.info(
            f"Successfully created {len(unique_modes)} ionization modes"
        )


async def update_sample_items_with_ionization_modes(
    batch_to_combination_mapping: dict[str, list[Any]], combinations: dict[tuple, Any]
) -> None:
    """
    Update sample items with their corresponding ionization_mode_id.
    This works with the original table structure before schema changes.

    :param batch_to_combination_mapping: Dictionary mapping batch_id to combination
    :param combinations: Dictionary mapping combination keys to ionization mode data
    """

    runtime.logger.info("Updating sample items with ionization_mode_id...")

    # Add "ionization_mode_id" column to "sample_item" table
    async with async_session() as session:
        await session.execute(
            text("ALTER TABLE sample_item ADD COLUMN ionization_mode_id VARCHAR(16)")
        )
        await session.commit()

    total_updated = 0

    for batch_id, combination_keys in batch_to_combination_mapping.items():
        # Get all sample items for this batch
        sample_items_response = await get_sample_items(sample_batch_id=batch_id)
        sample_items = sample_items_response.get("data", [])

        if not sample_items:
            continue

        for combination_key in combination_keys:
            combination_polarity = combination_key[2]

            sample_item_ids = [
                item["sample_item_id"]
                for item in sample_items
                if item["polarity"] == combination_polarity
            ]

            ionization_mode_id = combinations[combination_key]["ionization_mode_id"]

            async with async_session() as session:
                update_stmt = (
                    update(SampleItem)
                    .where(SampleItem.sample_item_id.in_(sample_item_ids))
                    .values(ionization_mode_id=ionization_mode_id)
                )
                result = await session.execute(update_stmt)
                await session.commit()

                updated_count = result.rowcount
                total_updated += updated_count
                runtime.logger.info(
                    f"Updated {updated_count} sample items in batch {batch_id} "
                    f"with ionization_mode_id {ionization_mode_id}"
                )

    runtime.logger.info(
        f"Successfully updated {total_updated} sample items with ionization mode IDs"
    )


async def modify_sample_item_schema() -> None:
    """
    Recreate sample_item table with updated schema in backup-and-recreate pattern.
    """
    runtime.logger.info("Recreating sample_item table with updated schema...")

    async with async_session() as session:
        # Disable FK enforcement during table recreation
        await session.execute(text("PRAGMA foreign_keys = OFF;"))

        # Step 1: Create backup table with all current data (including ionization_mode_id)
        await session.execute(
            text(
                """
                CREATE TABLE sample_item_backup AS
                SELECT * FROM sample_item;
                """
            )
        )

        # Step 2: Drop original table
        await session.execute(text("DROP TABLE sample_item;"))

        # Step 3: Create new table with updated schema using SQLAlchemy model
        connection = await session.connection()
        await connection.run_sync(SampleItem.__table__.create)

        # Step 4: Migrate all data back to the properly structured table
        await session.execute(
            text(
                """
                INSERT INTO sample_item (
                    sample_item_id, sample_batch_id, filename, sample_item_name,
                    sample_item_type, locked, sample_item_attributes,
                    filter_id, tic, polarity, ionization_mode_id, t0, t1,
                    sample_item_utc_created, sample_item_utc_modified
                )
                SELECT 
                    sample_item_id, sample_batch_id, filename, sample_item_name,
                    sample_item_type, locked, sample_item_attributes,
                    filter_id, tic, polarity, ionization_mode_id, t0, t1,
                    sample_item_utc_created, sample_item_utc_modified
                FROM sample_item_backup;
                """
            )
        )

        # Step 5: Clean up backup table
        await session.execute(text("DROP TABLE sample_item_backup;"))

        # Re-enable FK enforcement
        await session.execute(text("PRAGMA foreign_keys = ON;"))

        await session.commit()

    runtime.logger.info(
        "sample_item table recreated with updated schema including ionization_mode_id"
    )


async def modify_sample_batch_schema() -> None:
    """
    Remove build_params column from sample_batch table.
    """
    runtime.logger.info("Removing build_params column from sample_batch table...")

    async with async_session() as session:
        await session.execute(text("ALTER TABLE sample_batch DROP COLUMN build_params"))


async def update_sample_view() -> None:
    """
    Update the sample_view to reflect the new schema changes.
    """
    runtime.logger.info("Updating sample_view with ionization_mode_id field...")

    async with async_session() as session:
        await Sample.update_view(session)
        await session.commit()

    runtime.logger.info(
        "sample_view updated successfully with ionization_mode_id field"
    )


async def run():
    # Step 1: Create backup before migration
    await create_db_backup()

    # Step 2: Setup new database version
    old_version = 36
    new_version = 37
    old_db_path = os.path.join(runtime.config.database, f"mascope.v{old_version}.db")
    new_db_path = os.path.join(runtime.config.database, f"mascope.v{new_version}.db")

    # Copy database file to new version
    shutil.copyfile(old_db_path, new_db_path)

    # Step 3: Collect unique build params from old version
    await configure_database_engine(old_version)
    runtime.logger.info("Collecting unique build parameters from sample batches...")
    combinations, batch_to_combination_mapping = await collect_unique_build_params()

    # Step 4: Switch to new version and perform schema changes
    runtime.logger.info(
        f"Starting v{new_version} migration: create ionization_mode table and populate it."
    )
    await configure_database_engine(new_version)

    # Step 5: Create and populate ionization_mode table
    await create_ionization_mode_table()
    runtime.logger.info("Populating ionization_mode table...")
    unique_modes = list(combinations.values())
    await populate_ionization_modes(unique_modes)

    # Step 6: Update sample items with ionization_mode_id (original schema intact)
    await update_sample_items_with_ionization_modes(
        batch_to_combination_mapping, combinations
    )

    # Step 7: Apply schema changes with proper FK constraints
    await modify_sample_item_schema()
    await modify_sample_batch_schema()

    # Step 8: Update database views
    await update_sample_view()

    runtime.logger.info(f"Migration v{new_version} completed successfully!")


if __name__ == "__main__":
    asyncio.run(run())
