name: Mascope Release
run-name: ${{ github.actor }} is releasing Mascope

env:
  BRANCH: master
  
on:
  push:
    branches: [ master ]

jobs:
  
  # prep jobs
  
  release-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    outputs:
      version: ${{ steps.make_version.outputs.version }}
    steps:
      # setup
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create version tag
        id: make_version
        run: echo "version=$(git log -1 --date=format:"%Y.%m.%d" --format="%ad-%h")" >> "$GITHUB_OUTPUT"
      - name: Push version tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: ${{ env.BRANCH }}
          custom_tag: ${{ steps.make_version.outputs.version }}

  docker-build-push:
    runs-on: ubuntu-latest
    needs: release-tag
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker images
        run: |
          # install uv to run the CLI
          sudo snap install --classic astral-uv

          export MASCOPE_PATH=/home/runner/work/mascope/mascope/          
          VERSION=${{ needs.release-tag.outputs.version }}
          
          # execute build using the CLI
          uv run mascope prod build

          for service in backend frontend; do
            # alias image name
            IMAGE=ghcr.io/${{ github.repository }}/$service
            
            # tag with generated version and latest
            docker tag $IMAGE:latest $IMAGE:$VERSION
            
            # push to the github container registry
            docker push --all-tags $IMAGE
          done

