export { default as PaneAcquisitions } from './PaneAcquisitions.vue'
export { default as PaneBrowserSample } from './PaneBrowserSample.vue'
export { default as PaneBrowserTarget } from './PaneBrowserTarget.vue'
export { default as PaneDashSignal } from './PaneDashSignal.vue'
export { default as PaneProgress } from './PaneProgress.vue'
export { default as PaneSettingsCalibration } from './PaneSettingsCalibration.vue'
